### ISSUE TITLE
Updating Material-UI for research data tables breaks other code

### ISSUE THREAD

**Issue by keving17** [mit-teaching-systems-lab/threeflows#351]
I'm trying to use the new TablerSortLabel component in Material UI (see: https://material-ui-next.com/demos/tables/#sorting-amp-selecting) to allow educators to sort the data table by questions or students or whatever else they want.  However, it seems that upgrading the Material-UI library from v0.20.0 to v1.0.0-beta.38 breaks some of the existing material-ui components in our codebase. You can see this at commit https://github.com/mit-teaching-systems-lab/threeflows/commit/d50a04bf145c963e7f18dd133e2604666d871ec4.

I've taken a look at the first part that's broken. It seems that Material-UI has stopped supporting the AutoComplete component we use in https://github.com/mit-teaching-systems-lab/threeflows/blob/feature/authentication/client/src/message_popup/author/question_editing_components/students.jsx but they show a workaround using react-autosuggest (see: https://material-ui-next.com/getting-started/supported-components/).  

I remember the last time I tried doing something like this, the SelectField component in https://github.com/mit-teaching-systems-lab/threeflows/blob/feature/authentication/client/src/message_popup/playtest/hmtca_experience_page.jsx

I'm wondering if it is worthwhile for me to spend time upgrading our codebase to use the new Material-UI library or if I should just find another table library. Really all I want is a table that I can sort.

**Comment by keving17** [comment]
@kevinrobinson Can you take a look at this when you get a chance?

**Comment by kevinrobinson** [comment]
@keving17 This is awesome, great investigation! 👍 

We could go down this path and upgrade things, which would be good (and maybe even just remove some older code using those components that weren't not actively using, versus having to update those all too).  But I think that it might be worth checking out https://bvaughn.github.io/react-virtualized/#/components/Table first and see if that seems like it can help.  That library is aimed at "virtualizing" large component trees so you can give it a 50k row table and it will transparently optimize the rendering so it only actually renders the few that are onscreen at the time.  That's what renders all the data rows in the swipe right researcher view here: https://github.com/mit-teaching-systems-lab/swipe-right-for-cs/blob/f33016451128f6a8e05293963a3b362bddff213b/client/src/research/WorkshopsAnalysis.js#L104.

It might not be worth changing to `react-virtualized` here, but if there's some migration pain involved here to get sortable tables, it might be worth taking that migration pain to get sortable tables that will work will with large data sets too.

**Comment by keving17** [comment]
I'm going to close this issue since I used react-virtualized to make my table. I'll also delete the branch.
