### ISSUE TITLE
How does insecureStreamAudioFileFromS3 work??

### ISSUE THREAD

**Issue by keving17** [mit-teaching-systems-lab/threeflows#354]
I'm trying to get the audio players in ResearcherDataPage.js to fetch audio files from s3 and allow users to play the audio files in the browser.
<img width="748" alt="screen shot 2018-04-05 at 12 46 23 am" src="https://user-images.githubusercontent.com/11862658/38347673-cb28ba4c-386a-11e8-9658-553529b9342e.png">

I'm looking at insecureStreamAudioFileFromS3 at [audio.js](https://github.com/mit-teaching-systems-lab/threeflows/blob/master/server/endpoints/audio.js) and I have no idea how it works. Are there any examples of code that use this function? I wasn't able to find anything to hint towards how to use this.

My intuition is that I should be able to either

1. download the wav file and keep it in the background as some resource - similar to how we had originally downloaded the actual wav files and referenced them locally in the data table

2. generate some link that just allows me to stream the wav file when I hit play

How I'm understanding the code at insecureStreamAudioFileFromS3 is that we are grabbing an object from s3, streaming the audio as s3 sends it over and piping into the response object. However, I cannot find anything in the response object. There is a 200 response code indicating that something was successfully done but I can't figure out what happened.

I've started a new branch feature/getAudio where I assumed insecureStreamAudioFileFromS3 returned some wav file I could use at the source for a html audio object. Basically the source for the audio players start out as a pending promise, and then when the promise is resolved, I go back and find the audio element and update its source to whatever result I get back - intuitively, this result is whatever was grabbed from s3. However, this turns out to just be an [object Response] so I think I'm back where I have no idea how to extract the streamed audio from the response that it was piped into. You can see this at commit https://github.com/mit-teaching-systems-lab/threeflows/commit/c99325ad2d48e25c73706a777e4e2303066748c1.

Since the common problem seems to be not knowing how the piping s3 audio into the result object works, I'm playing around with concatenating all of the buffered data that is streamed in streamed and creating my own blob. Unfortunately, this bit seems to be getting more complicated and I fear I'm digging too far down into this rabbit hole.

Any thoughts/insights on how exactly to use insecureStreamAudioFileFromS3 would be very much appreciated. 🏳️

**Comment by keving17** [comment]
Hmmm, so I found a [resource](https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream) that seems to show how to extract the stream of data that was piped into the response.
<img width="756" alt="screen shot 2018-04-05 at 1 58 52 am" src="https://user-images.githubusercontent.com/11862658/38349458-334c9008-3875-11e8-9371-89e4c74116eb.png">

Using this, I sidestepped having to handle the buffers myself and used the original insecureStreamAudioFileFromS3 function to get a response with some streamed data in its body. I convert that response into a new response that just has the wav file in it and convert that into a blob that I insert into the source of my audio element. You can see this at commit https://github.com/mit-teaching-systems-lab/threeflows/commit/4eb4c1b8ab05309df8c4d86ba3d96abe334e4f3a.

I might be overthinking/overworking this but this seems to have worked.
<img width="749" alt="screen shot 2018-04-05 at 2 05 24 am" src="https://user-images.githubusercontent.com/11862658/38349607-d826d07a-3875-11e8-86eb-c37a780d417f.png">

**Comment by kevinrobinson** [comment]
@keving17 This is a great description!  And I think your intuition about overthinking is probably right on too :)  I can't dig in to help with this now, but I'd start with looking how `insecureStreamAudioFileFromS3` elsewhere in the codebase and using the same approach.  First see if you can get a WAV file from the server.

Similarly, as you're trying to figure out how to get an `<audio />` tag to play an audio file, look at how this is done elsewhere and use the same approach.  The UI code should be able to just say `<audio src={url} />` and have it play.

I don't think you'll have to work with the audio bytes directly, or to do anything with reading bytes of data from streams on the server or on the client (although that might be a helpful debugging step if things aren't working).  That being said, it's possible to write code and read all those bytes manually and get it to work, but you shouldn't have to since this will add code that's more complicated and make the server and browser do more work than the simpler approaches.

**Comment by keving17** [comment]
Yep. I think my final solution ended up finding a way around having to handle the audio bytes directly. It was a matter of grabbing the streamed audio from the response body and then turning that into a blob that could be put into `<audio src={blob} />`

**Comment by kevinrobinson** [comment]
@keving17 Nice, yeah grabbing a reference to the blob seems better for sure, and I think we'd have to dig into particular browser details to see how that compares to just setting the URL.  It sounds like one of the issues for using `<audio src={url} />` might be that this URL requires a particular HTTP header be sent for authorization as well.  A way to improve that and remove the audio handling code might be to exchange the token for a cookie from the server, which the browser would send.

Maybe not worth doing now but refactoring here (see https://github.com/mit-teaching-systems-lab/threeflows/pull/355/files#r180895608) would be another way to simplify - there's a lot going on with all that in the constructor :)
