### ISSUE TITLE
update-consent script doesn't work properly

### ISSUE THREAD

**Issue by keving17** [mit-teaching-systems-lab/threeflows#368]
I'm trying to have the update-consent script use environment variables so it will be able to use the DATABASE_URL variable in production. However, I can't seem to get this to run properly locally. From the code at commit https://github.com/mit-teaching-systems-lab/threeflows/commit/ecacc4b1a6e7fd025fd42f17f420abeeccc8d50b, when I change over to using the DATABASE_URL variable, even though I'm able to grab the DATABASE_URL variable, I no longer seem to be able to connect to the teacher-moments-db database. Instead, the script updates the consented_email table in my default postgres database. @kevinrobinson Do you have any ideas?
```
$ cat ./tmp/consented-latest.json | DATABASE_URL=http://localhost:5432/teacher-moments-db NODE_ENV=development yarn run update-consent
yarn run v1.2.1
$ node scripts/updateConsent.js
processing 320  emails
posgresUrl http://localhost:5432/teacher-moments-db
5 315
5 310
...
5 5
5 0
Done updating database.
```

**Comment by kevinrobinson** [comment]
@keving17 The docs for the node Postgres client (eg `new Pool`) sound like the place to chedk out: https://node-postgres.com/features/connecting.

**Comment by keving17** [comment]
Seems like the issue was that the Pool object needed an object needed an object literal as an argument where I was giving it a string. Fixed that up with
```
const pool = new Pool({connectionString:config.postgresUrl});
```
